// Code generated by "stringer -type=CarType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Sedan-1]
	_ = x[Hatchback-2]
	_ = x[MPV-3]
	_ = x[SUV-4]
	_ = x[Crossover-5]
	_ = x[Coupe-6]
	_ = x[Convertible-7]
}

const _CarType_name = "SedanHatchbackMPVSUVCrossoverCoupeConvertible"

var _CarType_index = [...]uint8{0, 5, 14, 17, 20, 29, 34, 45}

func (i CarType) String() string {
	i -= 1
	if i < 0 || i >= CarType(len(_CarType_index)-1) {
		return "CarType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CarType_name[_CarType_index[i]:_CarType_index[i+1]]
}
